name: mentally
description: A mental health Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.10
  go_router: ^12.1.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.2
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  volume_controller: ^2.0.7
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1

  timezone: ^0.9.2
  fl_chart: ^0.69.0
  google_generative_ai: ^0.4.3
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/audio/
    - assets/animations/
    - assets/icons/ 